#使用NumPy函数计算直方图
import cv2
import matplotlib.pyplot as plt
img = cv2.imread("D:\\demo1\\flower.jpeg")
plt.figure('程序运行结果：')
rgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
plt.subplot(2,2,1)
plt.imshow(rgb)
plt.title('Original')
plt.axis('off')
histb=cv2.calcHist([img],[0],None,[256],[0,255])
histg=cv2.calcHist([img],[1],None,[256],[0,255])
histr=cv2.calcHist([img],[2],None,[256],[0,255])
plt.subplot(2,2,2)
plt.plot(histb,color="b")
plt.plot(histg,color="g")
plt.plot(histr,color="r")
plt.title('hist')
img2 = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
hist = cv2.calcHist([img2],[0,1],None,[180,256],[0,180,0,256])
plt.subplot(2,1,2)
plt.title('2Dhist')
plt.imshow(hist)
plt.show()